### ISSUE TITLE
Add new Google Analytics Key to Header

### ISSUE THREAD

**Issue by adamajm** [CORaleigh/Visual-Town-Budget#11]

**Comment by adamajm** [comment]
I think here? 

https://github.com/CORaleigh/Visual-Town-Budget/blob/master/src/httpdocs/includes/template_elements/resources.php

**Comment by adamajm** [comment]
I think there may be some extra .js

**Comment by chrisgeyer** [comment]
need the url that we will be using in production so I can create it on our GA account and add the snippet

**Comment by adamajm** [comment]
openmaps.raleighnc.gov/budgetvisualization

**Comment by chrisgeyer** [comment]
add this to resources.php so it is included on everypage

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-9880547-7', 'auto');
  ga('send', 'pageview');
</script>

**Comment by chrisgeyer** [comment]
made this commit
