### ISSUE TITLE
Rename (Find/Replace):  “Visual-Town-Budget” to “budgetvisualization”

### ISSUE THREAD

**Issue by adamajm** [CORaleigh/Visual-Town-Budget#22]

**Comment by adamajm** [comment]
http://unix.stackexchange.com/questions/112023/how-can-i-replace-a-string-in-a-files

**Comment by justingreco** [comment]
Replaced Visual-Town-Budget with budgetvisualization in 19 files using Sublime Text.  Also updated the test server, application now is accessible at http://mapststarcsrv3/budgetvisualization
