### ISSUE TITLE
Expenses page does not display properly on refresh or using back button on browser

### ISSUE THREAD

**Issue by spencer44** [CORaleigh/Visual-Town-Budget#25]
Go to the expenses page. Zoom in on a particular department. For example the general fund http://mapststarcsrv3/Visual-Town-Budget/expenses/2014/t/26bfd1ff  and that URL does not display properly when directly linked or if you leave that page and go back.

**Comment by justingreco** [comment]
added the subdirectory name (/Visual-Town-Budget/) to the beginning of the css and js paths in the index.php and imports.php files.
