### ISSUE TITLE
Budget visuals completely distorted with IE 11

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/Visual-Town-Budget#35]
The budget data and visuals are distorted and unusable when viewed with IE 11. See attached

![bv via ie](https://cloud.githubusercontent.com/assets/10038645/7588405/de444010-f88a-11e4-8be5-7dfe5e45238f.jpg)

**Comment by adamajm** [comment]
Update: avlbudget.org works in IE11 so the answer should be in the code...

**Comment by chrisgeyer** [comment]
ie11 getting this javascript error in the console:
SCRIPT5007: Unable to get property 'prototype' of undefined or null reference
File: d3.v3.min.js, Line: 2, Column: 26629

**Comment by adamajm** [comment]
Breaks on var fa=ca.CSSStyleDeclaration.prototype

Here are the lines from the debugger:
(){return+new Date});var oa=document,ca=window;try{oa.createElement("div").style.setProperty("opacity",0,"")}catch(la){var fa=ca.CSSStyleDeclaration.prototype,sa=fa.setProperty;fa.setProperty=function(n,t,e){sa.call(this,n,t+"",e)}}aa.ascending=function(n,t){return t>n?-1:n>t?1:n>=t?0:0/0},aa.descending=function(n,t){return n>t?-1:t>n?1:t>=n?0:0/0},aa.min=function(n,t){var e,r,i=-1,u=n.length;if

**Comment by chrisgeyer** [comment]
while ashevilles budget explorer displays on load it is non interactive in IE11 getting this error
HTML1300: Navigation occurred.
File: 9e832f0b
[object Object]
{

**proto**: { },
mode: "t",
node: "9e832f0b",
section: "revenues",
year: "2014"
}

SCRIPT5007: Unable to get property 'setProperty' of undefined or null reference
File: d3.v3.min.js, Line: 1, Column: 3047

**Comment by sardeenz** [comment]
It's a default setting in IE11 for sites inside CORALEIGH domain. If you go to Tools - Compatibility view settings, and uncheck compatibility mode for intranet sites, then it loads the visualization.

**Comment by ejaxon** [comment]
So does this mean this issue is closed? Just got around to looking, but it looks like you've got it figured out.
