### ISSUE TITLE
Add Chart of unidentified projects to capital page

### ISSUE THREAD

**Issue by adamajm** [CORaleigh/Visual-Town-Budget#36]
add chart of PRCR projects with "unidentified" location to 
http://mapststarcsrv3/Visual-Town-Budget/capital/

**Comment by chrisgeyer** [comment]
pushed a commit for this now

**Comment by adamajm** [comment]
move chart to top div under Nav. ADD the "read more" link:
http://jedfoster.com/Readmore.js/

**Comment by chrisgeyer** [comment]
have added the script and functionality on the capital improvements page. let me know how you would like to tweak it.
