### ISSUE TITLE
IE 11 - Unable to drill down on any of the visuals

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/Visual-Town-Budget#39]
With Chrome or FF, if I click General Funds it drills down to Non-Program Revenues. With IE there is no drill down capability on any of the visuals.

**Comment by justingreco** [comment]
Issue with D3 and IE11, checked Asheville's version at avlbudget.org and the same issue occurs.  Checked the original Arlington, MA version and it works.

**Comment by justingreco** [comment]
Looks like Arlington resolved this issue here:
https://github.com/goinvo/Visual-Town-Budget/issues/25

**Comment by adamajm** [comment]
here's the relevant commit (I think): https://github.com/goinvo/Visual-Town-Budget/commit/1c1db3b8339d543e01c7c978411c068d97dbe8f0

**Comment by justingreco** [comment]
duplicate of #38

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
