### ISSUE TITLE
Add Twitter Sharing and/or a simple "Like" feature

### ISSUE THREAD

**Issue by adamajm** [CORaleigh/Visual-Town-Budget#40]
Share button via Tweet (instead of "Feedback") icon with pre-filled text. "Check out the proposed FY16 @Raleighgov budget with visualization app via @OpenRaleigh #opendata"

**Comment by justingreco** [comment]
https://dev.twitter.com/web/tweet-button

**Comment by adamajm** [comment]
****
a class="twitter-share-button"
  href="https://twitter.com/intent/tweet?text=Check%20out%20@OpenRaleigh%20Budget App%20">
Tweet</a>

**Comment by chrisgeyer** [comment]
added share link to header with icon
