### ISSUE TITLE
Add IE Upgrade warning script (for IE 8)

### ISSUE THREAD

**Issue by adamajm** [CORaleigh/Visual-Town-Budget#41]
See: http://browser-update.org/ 

This snippet prompts users of lower browser version than IE10 to upgrade their browser

---

script> 
var $buoop = {vs:{i:9,f:15,o:12.1,s:5.1},c:2}; 
function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>

**Comment by justingreco** [comment]
message has been added and appears in IE 9 and below

**Comment by chavisa** [comment]
Closed
