### ISSUE TITLE
Give Site Feedback form displays incorrect error message

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/Visual-Town-Budget#50]
The form that is displayed when the 'Give Site Feedback' link is selected, has an 'Other' field and 'What features would you like to see added to the website' field, where free text can be added. I entered too much data (1000 characters) into each of these fields expecting to get an message indicating a limit, but one did not display. When I selected the submit button I got an error message, 'Sorry the file you requested does not exist'.

The expectation is that each of these fields will only allow a max amount and if that is exceeded an error message communicates that.

![too much data in other field](https://cloud.githubusercontent.com/assets/10038645/7659654/8d916da8-fb11-11e4-8a56-8d5b31413176.jpg)

**Comment by adamajm** [comment]
Thanks Allen. I also tried entering a lot of data but didn't get an error message. I think this is a minor issue.  We are not expecting such extensive site feedback based on previous experience.

**Comment by chavisa** [comment]
Closed.
