### ISSUE TITLE
The Search feature on the Capital Improvements page seems to be overkill

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/Visual-Town-Budget#51]
The 'Search' feature on the Capital Improvements page will allow a user to find any location in the world. I typed in 'Bicycle' and was able to find  The Bicycle House, Suan Phak Rd., Taling Chan, Bangkok .  Type in 'America' and it displays a map of the US. In grade schopol I attend "Ashley Elementary School, Fayetteville, NC'. I typed they in and it located it on the map.

It just seems a bit much. I think it should be removed or limited to the City.

**Comment by adamajm** [comment]
Thanks Allen, I have limited the search to the "extent" of the map at the "Home" level

**Comment by chavisa** [comment]
Closed
