### ISSUE TITLE
The legends On Captial Improvments have errors

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/Visual-Town-Budget#52]
On the left side of the Capital Improvement page,  there is a double arrow, which when clicked displays several legends. Please review for these legends for the following: (from bottom to top) :
1. Public Utilizes (Sewer Upgrades and Facilities), Transportation, General Public Improvements, Parks, Recreation, Cultural Resources Trails, and Parks, Recreation, Cultural Resources each have an entry of < 0. Is that correct? I would assume that should be changed to simply '0'

2.The Storm water legend top value is currently '> 3,550,000 to 3,550,000'. I think this should just be "> 3,550,000'

![stormwater](https://cloud.githubusercontent.com/assets/10038645/7660764/16da047c-fb1b-11e4-81a7-ae18bff8dac3.jpg)

**Comment by adamajm** [comment]
Thanks Allen - I have updated the legend settings per your observations

**Comment by chavisa** [comment]
Closed.
