### ISSUE TITLE
Zoom '-' displays the world map should be limited to the City

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/Visual-Town-Budget#53]
On Capital Improvements page, currently the Zoom '-' button can be continually selected until it displays the world map. Should be limited to just the City.

![zoom - button displays the world](https://cloud.githubusercontent.com/assets/10038645/7661052/6ff6796c-fb1d-11e4-8d9a-9031dff9e5a2.png)

**Comment by justingreco** [comment]
This map was created in ArcGIS Online and the product does not support setting a limit on the zoom level.

**Comment by chavisa** [comment]
Closed.
