### ISSUE TITLE
This comma is small but driving me nuts!

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/Visual-Town-Budget#56]
This is just a small grammatical error; there is an extra space before the comma after 'The City of Raleigh', 

Currently = Raleigh , 
Change to = Raleigh,
![comma](https://cloud.githubusercontent.com/assets/10038645/7666051/e66da76c-fba1-11e4-87d2-b82e3818bb1a.jpg)

**Comment by chrisgeyer** [comment]
fixed this spacing issue

**Comment by chavisa** [comment]
Closed
