### ISSUE TITLE
Not sure if this is an issue - Revenue and Expenses data is exactly the same

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/Visual-Town-Budget#59]
I don't know if this is a problem or not, but I've notice the data is exactly the same between Revenue and Expenses.

Follow these steps:
1. Used any browser, refresh the screen
2. Click Revenue, Tabular view, Year = 2012
2a. Make a screen print of the data
3. Click Expenses, Tabular view, year = 2012
3a. Make a screen print of the data

The Expense data is an exact match of the Revenue data. How can Expense data and Revenue data be an exact match and be accurate?

**Comment by adamajm** [comment]
Due to balanced budget requirements, this should be the same at least at the high levels.

**Comment by adamajm** [comment]
Budget signed off
