### ISSUE TITLE
rip out uneccessary pages

### ISSUE THREAD

**Issue by sardeenz** [CORaleigh/Visual-Town-Budget#8]
landing page should be /expenses page

Keep pages but Remove from top level Navigation: 
- Resources
- About this Project

**Comment by adamajm** [comment]
https://github.com/CORaleigh/Visual-Town-Budget/blob/master/src/httpdocs/includes/template_elements/nav.php

**Comment by adamajm** [comment]
https://github.com/CORaleigh/Visual-Town-Budget/blob/master/src/httpdocs/includes/template_elements/top-bar.php
